apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka-cqrs
spec:
  type: NodePort
  selector:
    app: kafka-cqrs
  ports:
  - name: zookeeper-port
    protocol: TCP
    port: 2181
    targetPort: zookeeper-port
    nodePort: 31001
  - name: kafka-port
    protocol: TCP
    port: 9092
    targetPort: kafka-port
    nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cqrs
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
    spec:
      containers:
      - name: kafka
        image: spotify/kafka:latest
        ports:
          - containerPort: 9092
            name: kafka-port
          - containerPort: 2181
            name: zookeeper-port
---
apiVersion: v1
kind: Pod
metadata:
  name: test-client
spec:
  restartPolicy: Never
  containers:
  - name: test-client
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "ping -c 2 kafka"]
