apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-cqrs
spec:
  selector:
    app: kafka-cqrs
    service: kafka-service
  ports:
  - name: kafka-service-port
    protocol: TCP
    port: 9092
    targetPort: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-cqrs-kafka-service
  labels:
    app: kafka-cqrs
    service: kafka-service
spec:
  selector:
    matchLabels:
      app: kafka-cqrs
      service: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-cqrs
        service: kafka-service
    spec:
      containers:
      - name: kafka-service
        image: bitnami/kafka:1.1.1
#        image: ches/kafka:0.10.2.1
        ports:
          - containerPort: 9092
        env:
#          - name: ZOOKEEPER_IP
#            value: zookeeper-service
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service:2181
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://kafka-service:9092
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://localhost:9092

